# Generated by Django 4.0.10 on 2023-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_localitypage_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localitypage',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localitypage',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
